---
name: manual
run-name: build ${{inputs.version}}
env:
  upstream: BurntSushi/ripgrep

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: version to build (without "v")
        default: 13.0.0
        type: string

permissions: write-all
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {target: aarch64-unknown-linux-gnu, os: ubuntu-latest, cross: true}
          - {target: aarch64-unknown-linux-musl, os: ubuntu-latest, cross: true}
          - {target: aarch64-apple-darwin, os: macos-latest, cross: false}
          - {target: x86_64-unknown-linux-gnu, os: ubuntu-latest, cross: false}
          - {target: x86_64-unknown-linux-musl, os: ubuntu-latest, cross: false}
          - {target: x86_64-apple-darwin, os: macos-latest, cross: false}

    name: Build ${{matrix.target}}
    runs-on: ${{ matrix.os }}
    env:
      CARGO: cargo
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          repository: ${{env.upstream}}
          ref: ${{inputs.version}}

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install musl-gcc on Linux
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Install Cross
        if: matrix.cross
        run: |
          cargo install cross --git https://github.com/cross-rs/cross.git
          echo "CARGO=cross" >> $GITHUB_ENV

      - name: Set profile.release.strip = true
        shell: bash
        run: |
          mkdir -p $HOME/.cargo
          cat >> $HOME/.cargo/config.toml <<EOF
          [profile.release]
          strip = true
          EOF

      - name: Build release binary
        run: |-
          ${{ env.CARGO }} build --release --locked --target ${{ matrix.target }}

      - name: Upload ${{matrix.target}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          mv "target/${{ matrix.target }}/release/rg" ./rg
          tar -czf "ripgrep-${{inputs.version}}-${{matrix.target}}.tar.gz" rg
          # create release if not exist
          gh release create "${{inputs.version}}" --notes "Release ripgrep ${{inputs.version}}" --title "${{inputs.version}}" --repo "${{github.repository}}" || true
          # delete the asset if exists
          gh release delete-asset "${{inputs.version}}" "ripgrep-${{inputs.version}}-${{matrix.target}}.tar.gz" --yes --repo "${{github.repository}}" || true
          gh release upload "${{inputs.version}}" "./ripgrep-${{inputs.version}}-${{matrix.target}}.tar.gz" --repo "${{github.repository}}"
